name: Automating Image Pipelines with Packer

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
        unzip -o packer_1.7.4_linux_amd64.zip
        sudo mv packer /usr/local/bin/packer_new
        sudo mv /usr/local/bin/packer /usr/local/bin/packer_old
        sudo mv /usr/local/bin/packer_new /usr/local/bin/packer
        packer --version




    - name: Build Image
      run: packer build image.pkr.hcl

    # Add deployment steps if needed
