name: Automating Image Pipelines with Packer

on:
  push:
    branches:
      - master 
jobs:

  Golden-Image:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

    - name: Install Packer

      run: |

        wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip

        unzip packer_1.7.6_linux_amd64.zip

        sudo mv packer /usr/local/bin/

      shell: bash
 
    - name: Display Packer Version

      run: packer version

    - name: build packer

      run: packer build tomcat8_ojdk8.json
